name: Update Readme Stats
# This will pull latest info from Wakatime

on:
  schedule:
    # Runs everyday at midnight
    - cron: '0 0 * * *'

jobs:
  update-readme:
    name: Profile Readme Development Stats
    runs-on: ubuntu-latest
    steps:
      - uses: deepfriedfilth/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{secrets.WAKATIME_API_KEY}}
          GH_TOKEN: ${{secrets.GH_TOKEN}}
          SHOW_LINES_OF_CODE: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_COMMIT: "False"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_PROJECTS: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_LOC_CHART: "False"

