name: Update Readme Stats
# This will pull latest info from Wakatime

on:
  schedule:
    # Runs at everyday at midnight
    - cron: '0 0 * * *'

jobs:
  update-readme:
    name: Profile Readme Development Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@V3
        with:
          WAKATIME_API_KEY: ${{secrets.WAKATIME_API_KEY}}
          SHOW_LINES_OF_CODE: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_PROJECTS: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_LOC_CHART: "False"

